### ISSUE TITLE
Driver not working with ST25DV64K chip variant.

### ISSUE THREAD

**Issue by tandronescu** [STMicroelectronics/mbed-nfc-st25dv#1]
Attempting to use NFC for a project using the ST25DV chip family. I was able to setup the driver and compile it successfully in the mbed-os environment using a Nucleo F446RE. Using the [ANT7-T-ST25DV04K](https://www.st.com/en/evaluation-tools/ant7-t-st25dv04k.html) reference board (which uses the 4k variant of the chip), I was able to successfully run some sample code write a URL to the tag (using the program structure here: https://os.mbed.com/teams/mbed-os-examples/code/mbed-os-example-nfc-EEPROM//file/eb8ecd3272a1/source/main.cpp/). My phone is able to read it perfectly. 

For this project, more space is required so I created a simple PCB using the 64k version of the chip. However, it appears the driver is not working correctly. I get a constant stream of errors starting with error code 16 (controller error) followed by continuous error code 1's (unknown error):
```
Building an ndef message 
failed to write (error: 16)
failed to read (error: 1)
failed to write (error: 1)
failed to read (error: 1)
```

Attaching a debugger to my nucleo reveals that after going through write_ndef_message() in NFCEEPROM.cpp and setting _current_op, it builds the ndef message correctly then gets an error after trying to write. The error is traced to on_bytes_written() in NFCEEPROM.cpp which does not give any useful information. It simply says this error should not happen, the state machine is broken or driver is doing something wrong. 

So it appears the EEPROM is being initialized correctly because it is passing this portion of the code, but the driver fails to write the data. I am using the exact same code and connections that work for the 4k variant of the chip. I've triple-checked all the electrical connections on the PCB and scope output shows the I2C lines are writing the same raw data. Is the driver not meant to work with other variants of the chip? The driver code appears to check for either the 4k variant or the 64k variant on line 262, shown below:
```
/* Check if it is the wanted chip */
if( (nfctag_id == I_AM_ST25DV04) || (nfctag_id == I_AM_ST25DV64) )
{
  _is_device_inited = true;
  Nfctag_Drv = &St25Dv_i2c_Drv;
  Nfctag_Drv->pData = &St25Dv_i2c_ExtDrv;
}
```
Any help would be appreciated. I attached call stack trace output picture below and the relevant error.
![image](https://user-images.githubusercontent.com/30327537/152272482-62a1e274-4050-42c3-93df-5019cf3551e0.png)
![image](https://user-images.githubusercontent.com/30327537/152272491-9187c3d3-31c6-4eab-ad98-a0ab9276916e.png)

**Comment by mgrella** [comment]
Hello, sorry for late answer.
This repository is actually not maintained any more and will be archived shortly.
Up to date offer by STMicroelectronics related to NFC can be found, for example, in the NFC4 package:
https://github.com/STMicroelectronics/X-CUBE-NFC4

With best regards.
